spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: system
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  h2:
    console:
      enabled: false